###################################################################################################
# Contains the URL and checksums to download version 6.0.2 of the x86 64-bit ASP .Net runtime
# from Microsoft.
# Copyright Richard Dunkley 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/2611908d-446f-45ec-be23-57feaf859d7e/90bb871b0097b874c6de0b1a1b629c31/aspnetcore-runtime-6.0.2-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "ae9abc845a88cc75b9c8555ec5c26c9a"
SRC_URI[sha256sum] = "6bd6ceb4a3d04734668b3201c1e7e15825fe63fde189e5b7fb5479fd9dcd751c"
