###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/ee1fd04f-606d-4bd6-ad2d-1a902af87ca9/d8c3c09f00cb010c0af0922870ba5b04/aspnetcore-runtime-3.0.0-preview5-19227-01-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "a6a54194844edd8864d408194a4d28a5"
SRC_URI[sha256sum] = "f275570628386bbd04afb7d394eb9e0f66d4a0c7afa9ab65ddab86c28b3e92bc"

