###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/2d6d851a-4eea-4a7a-9d5e-f1d6cdccda29/366a3dd90251ce11d8c5191ae9633efc/aspnetcore-runtime-7.0.0-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "acc88a73cb54ace1cfe856cf941fed7a"
SRC_URI[sha256sum] = "6e8698b13ddd26d2809f5e53f8a0e5a7c7703ab8f20ba7f08c2ff49002cf5caa"
