###################################################################################################
# Contains the URL and checksums to download version 6.0.2 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/d30e9e2e-10a5-46c6-9b81-1a6a965d6739/6f56a3893b16fa841c8cb34ec9b3768d/aspnetcore-runtime-6.0.2-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "b3a1d1bb4a55dfd53638987fae378552"
SRC_URI[sha256sum] = "49b6526f272579cf7d09e597d43b7caa4d6f9ee07142b96727ca7b2fc5b5f18c"
