###################################################################################################
# Contains the URL and checksums to download version 6.0.14 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/0a569135-1e0d-4273-ab56-f732a11f6199/6fb7eb4813c1cc1a7354cb665d2389c3/dotnet-sdk-6.0.406-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "8c6a32505bc44da9f107a00f2381ef73"
SRC_URI[sha256sum] = "abe1f3f2c9b3e2c8e539703c11753fa7d44ded4744cab1ecd1d463d352dcea49"
