###################################################################################################
# Contains the URL and checksums to download version 6.0.11 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/57b2bdaf-8455-4b1a-b25b-5950c950bd38/471d6de036e6f367f3a4aae5252d885a/aspnetcore-runtime-6.0.12-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "af368f975fcd18ad6326382fc64594dd"
SRC_URI[sha256sum] = "2131903c85087017ec680e44676c4eb46e7bd0a12f0683c2a7790ec75b243d75"

