###################################################################################################
# Contains the URL and checksums to download version 3.1.3 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/7faca87b-7526-4dcd-ae23-4559d2c51ce3/7db1f314c733191ea43e1757e3b2583d/aspnetcore-runtime-3.1.3-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "65e39a67baf8823ea86b946e3243168d"
SRC_URI[sha256sum] = "34cc5c7f16b45234603d9f352a1bd3997d5e07d7380c49266860f75dbc29146d"
