###################################################################################################
# Contains the URL and checksums to download version 2.2.8 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/9fcb0171-11d7-40e6-a2e8-2357813bf6bd/becdd52523d5a6782ded8febd2c487a0/aspnetcore-runtime-2.2.8-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "f06f58e1ca7f7c2ad9a7264eed31a171"
SRC_URI[sha256sum] = "933d37f4ad79bab926df9790606f8b7016a7560cad2a9ae8c00d38f81ae53649"
