###################################################################################################
# Contains the URL and checksums to download version 3.1.8 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/f7c8f82a-8c47-497d-875b-2ac210599ec5/e8aea0c195efed8a9aff2ba687db8c26/aspnetcore-runtime-3.1.8-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "e116dd29ebf80792a2246c66fb729cd1"
SRC_URI[sha256sum] = "823f8ea555fd56ab40d56d423748036204c4540c08baa61de4462978a0c35583"
