###################################################################################################
# Contains the URL and checksums to download version 3.1.8 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/ac555882-afa3-4f5b-842b-c4cec2ae0e90/84cdd6d47a9f79b6722f0e0a9b258888/aspnetcore-runtime-5.0.0-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "f5e6d1dfcd53ae61cd601bd2bb5d9b5f"
SRC_URI[sha256sum] = "15227edfc59e51cae4bd32e59c015b4e743642a45780ee80760146792a2044d6"
