###################################################################################################
# Contains the URL and checksums to download version 5.0.17 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2023
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/6eb8aee2-cbea-4c4f-9bb9-ea6229ec229b/d6c438e5071c359ad995134f0a33e731/aspnetcore-runtime-5.0.17-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "a9b8ab011d70de3a63cd88e3b01da72d"
SRC_URI[sha256sum] = "4d920ed925e98a0fb5d7bde63631e851d61e1e0fb5349398c826133d85b41d73"
