###################################################################################################
# Contains the URL and checksums to download version 6.0.0 of the x86 64-bit ASP .Net runtime
# from Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/a8dd1c9d-1a47-4135-8ad8-7091ff6bbe1e/6af53c3eee71038248937daf4599f06a/aspnetcore-runtime-6.0.0-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "8a1872969546c838cfca33da33532f87"
SRC_URI[sha256sum] = "e30fcd2106c0703b8beef57c3af3447310d25865e5ebbb21cfcaca51d6ac17e0"
