###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2023
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/d1302c30-5719-413a-9090-56a8725cabe9/4f505eba5fb19dd85a5c837475579ef2/aspnetcore-runtime-7.0.10-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "7f4de191c620832bb8be9a81a926f991"
SRC_URI[sha256sum] = "bca4ebd94f07e72f6940f54b3677baf9ed7b7490f9bb6e20194803ec4d4f3d87"

