###################################################################################################
# Contains the URL and checksums to download version 3.1.8 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/390b186e-eefc-4dab-a5bb-1c549970771b/6dacdae3ab014ed7e2d7f10e233211db/aspnetcore-runtime-3.1.8-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "d2e94361c874a195d89a19359bde6e89"
SRC_URI[sha256sum] = "e314b0076ad23a4bc457f87b186e1e039079d326d13997e056af9e5690707339"

