###################################################################################################
# Contains the URL and checksums to download version 5.0.0 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/1c5366e8-9b74-4017-96ae-47fc08832c22/504aed87590bd99c49d053bc6f980b6b/aspnetcore-runtime-5.0.0-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "edfb726fbbea89b54786f4d09e33d6f9"
SRC_URI[sha256sum] = "c9077c6cd0985a0f327bcf2735dff0f30978387dbd311e2bcdf2c14760b5fe96"

