###################################################################################################
# Contains the URL and checksums to download version 7.0 of the x86 64-bit ASP .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/4bbb4d31-70ba-4def-b747-4358be873982/3dbca5b64c2ffb88641c0e42bdeb297a/aspnetcore-runtime-7.0.0-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "3d03bc3b64f3f58705277051294863db"
SRC_URI[sha256sum] = "27753c368cc075e23fe2c23063be252f54d19194a004b178b4faab1ba2e8af8d"
