###################################################################################################
# Contains the URL and checksums to download version 2.2.7 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/ea963afd-3b38-46c1-b058-c4ccbf862e48/6edc7bde8816cb981e8d0c1e5bf21718/aspnetcore-runtime-2.2.7-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "bdfd4d7c11ee10e2f5ee6a9c20b46e0a"
SRC_URI[sha256sum] = "d6a9e690d07724ca618f3b9e9135104eb98ec694cfe823d06027e1cec22affdf"
