###################################################################################################
# Contains the URL and checksums to download version 2.2.8 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/e716faa4-345c-45a7-bd1f-860cdf422b75/fa8e57167f3bd4bf20b8b60992cf184f/aspnetcore-runtime-2.2.8-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "212a8b758c37f789ba56470b04a9e820"
SRC_URI[sha256sum] = "e0f5383b89afcde037510bdd06c2f584d6593e28b9824f322b55a1b04bd0ccf2"
