###################################################################################################
# Contains the URL and checksums to download version 6.0.14 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/4fac9144-1998-4d99-8000-6f8c8a19e9a3/3d722a6e310cf82c898f91138971be5b/aspnetcore-runtime-6.0.14-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "43d35fe8febe961e9c42c3303e20a208"
SRC_URI[sha256sum] = "da7f9e231476cfb5f52f1f469a1ef22b5bb052a0ce53af97b21b70bca0abef0a"

