###################################################################################################
# Contains the URL and checksums to download version 3.0.1 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/67362f50-42cc-42d0-919f-c868e8a70db8/3ecdc7b53899df7e2e260b6b7b3f25c1/aspnetcore-runtime-3.0.1-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "802b481d0c50599cf1f646c22571ea09"
SRC_URI[sha256sum] = "21e578933c272f4834b9080002ba8551108cf9257a557594b49e727d972df565"
