###################################################################################################
# Contains the URL and checksums to download version 6.0.12 of the x86 64-bit ASP .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/4ba0f30d-0a77-4997-8d8d-1b113d60253b/5caeeb07572b0b6a26f2a82f7a4eb31d/aspnetcore-runtime-6.0.12-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "41b2e52c52f116ee68bdd5da53306fa8"
SRC_URI[sha256sum] = "dd60c551d63eb66cd9bdc7ef223c00f49341e67f8ddda2e4ab412c3ee8997765"
