###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/246ddf4f-e4b8-4306-8761-2dfbca37f7de/274b8c00abf99f374729e0534779951e/aspnetcore-runtime-3.0.0-preview6.19307.2-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "881faef29cf865f25384412d5a45a991"
SRC_URI[sha256sum] = "e27e1b4c9f4e7627038ba3b2078322c8a158155a771d44e53da7e80375f2c9bc"


