###################################################################################################
# Contains the URL and checksums to download version 3.1.10 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/a2223d1f-c138-4586-8cd1-274c5387e975/623ece755546aca8f4be268f525683c5/aspnetcore-runtime-3.1.10-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "b79becc4145571b44ded99be4cb0e601"
SRC_URI[sha256sum] = "29c6aa914739dce59e04d1fc7dceb33e97dfec6624ec3c297a8375f66aece092"

