###################################################################################################
# Contains the URL and checksums to download version 6.0.8 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/cf567026-a29a-41aa-bc3a-e4e1ad0df480/0925d411e8e09e31ba7a39a3eb0e29af/aspnetcore-runtime-6.0.8-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "94030b9cd2be902e297981f453057427"
SRC_URI[sha256sum] = "8e53a2bf2d145c8983b85db1e1010bdf257f0d30beedaaa34a602e69ca4d74bf"

