###################################################################################################
# Contains the URL and checksums to download version 6.0.11 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/4072393d-3350-41d2-98e2-dc46fd930fae/6f09e1d7685fbbc01f6d84b1140e1b49/aspnetcore-runtime-6.0.11-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "636934aa0ff2e77ea85da787307b6760"
SRC_URI[sha256sum] = "4bec937852e3a0660a57243c19a5b1d2375047de2aa1df972bc587b410ea660b"

