###################################################################################################
# Contains the URL and checksums to download version 3.1.3 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/c8cd43dd-e9de-4ff9-9cea-2f02fba6869c/d5c653c12ec93cb71e30b21856acea66/aspnetcore-runtime-3.1.9-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "9a24eb9b02f03eee76a397ca11c9c7cf"
SRC_URI[sha256sum] = "496247dc5098a506accb0c3286f82e497a6da30f4d0b8262c29484c096d5f717"

