###################################################################################################
# Contains the URL and checksums to download version 3.1.8 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/6e4ebb4a-9369-4140-a673-3d26e96662e7/75273b1fb5f1141e1b98008a0c1baaa5/aspnetcore-runtime-5.0.0-rc.1.20451.17-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "87329ef6595b9be2a062c81ee79a43f5"
SRC_URI[sha256sum] = "d04b6598aebdd865995bc6ee086676e47c56706ef2c5b6926b87a64bb7f4c8e5"
