###################################################################################################
# Contains the URL and checksums to download version 6.0.8 of the x86 64-bit ASP .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/5cc06c3a-4d8a-4fb2-8f7a-ecd23cd8c4e0/dd386c0e3a41ea54f459907c834acedf/aspnetcore-runtime-6.0.8-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "5e05baa56ecf343068f941844fc55d6c"
SRC_URI[sha256sum] = "2bd3c32aacacbb6963df523e1022bc1989f7f1efc0de87d458cd3721dfafc42b"
