###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/a8f84ed3-7294-427c-883a-5278091d63ab/373f6fa1ef32f798c2fd3ba98b657249/aspnetcore-runtime-3.0.0-preview5-19227-01-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "3e7f0797320ec8c9217a4d98bfb85604"
SRC_URI[sha256sum] = "22bf8bf326821776a2b9a3c76c7b1bc99f628540b4bb38a44d31d630f6ec3991"


