###################################################################################################
# Contains the URL and checksums to download version 3.1.0 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/e7c893c5-726a-40aa-8a13-7ae6f1e3ee4e/8ba7467756a3fb1778f02f1ca98ca1ee/aspnetcore-runtime-3.1.0-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "2d5a2cbf3216ae68a2570ff6173aa862"
SRC_URI[sha256sum] = "9db3e06d701e36d21a3f44ec7dfe16c60c54f21cb352890a8956f9e5f3677143"
