###################################################################################################
# Contains the URL and checksums to download version 3.1.3 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/dffd493f-9eb8-483f-81c7-a9e2201574ef/54e7464241e01e7031fd89e6fe88e6da/aspnetcore-runtime-3.1.9-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "dc009a1346bc1be92962e3c95644350a"
SRC_URI[sha256sum] = "1ffe06b0012feb52d75e748438695e11905343890de73a594e6540d535fd084c"
