###################################################################################################
# Contains the URL and checksums to download version 2.2.7 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/f0b6c052-2f5d-42b9-8ffa-870ea2a60d11/90c1d5b4a2548c1beaeacff0a39a459c/aspnetcore-runtime-2.2.7-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "2d60c1166bfbd29f7ec0cc062f7fe926"
SRC_URI[sha256sum] = "e9872e53b834e2c3194710cc2b242bb17a00f1a8b1f42df6e4b87d2ea1ed935e"
