###################################################################################################
# Contains the URL and checksums to download version 5.0.12 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/bfc8ae06-2830-4082-a09e-63b3c7134096/880a4712d4ba3491c88aa566553c4e8a/aspnetcore-runtime-5.0.12-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "9961a72cb0c59620ea82c77f961090a6"
SRC_URI[sha256sum] = "8c311d23e99d7a981745e1773bc850fc22e431fb57786a93a299b0f139b095aa"
