###################################################################################################
# Contains the URL and checksums to download version 5.0.14 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/f56adf04-e4a8-48bf-b2e2-722e7206a4f2/7f40d4ebeff281120ba76e7b091356b0/aspnetcore-runtime-5.0.14-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "f5a169bc2895903a93b29962723756b5"
SRC_URI[sha256sum] = "7e1cf5abc591985f4087650cc2cb599caa046004f8b08e2b81199c63dbc0681c"
