###################################################################################################
# Contains the URL and checksums to download version 3.1.10 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/eca743d3-030f-4b1b-bd15-3573091f1c02/f3e464abc31deb7bc2747ed6cc1a8f5c/aspnetcore-runtime-3.1.10-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "17193301d24d1bab720fe21876ce1536"
SRC_URI[sha256sum] = "b58376e76c68f03e142ac9a771b782cb7be926a16e920d83c711903b82608f3a"
