###################################################################################################
# Contains the URL and checksums to download version 6.0.14 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/10762208-8896-423a-b7f3-5084c7548ce7/620af5c42e5a4087478890294dbe39fb/aspnetcore-runtime-6.0.14-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "43d35fe8febe961e9c42c3303e20a208"
SRC_URI[sha256sum] = "da7f9e231476cfb5f52f1f469a1ef22b5bb052a0ce53af97b21b70bca0abef0a"
