###################################################################################################
# Contains the URL and checksums to download version 6.0.21 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2023
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/d184fca4-527b-46aa-ad71-9fdf7c010262/dc0eb0bd54951de8c1eacaab795ecf24/aspnetcore-runtime-6.0.21-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "26345ac3baaa27f0651499323ed3aa23"
SRC_URI[sha256sum] = "d319439c053b96dd130bcad06f0a920f08b73659808cef61bc5e306bae755eed"

