###################################################################################################
# Contains the URL and checksums to download version 3.1.10 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/936a9563-1dad-4c4b-b366-c7fcc3e28215/a1edcaf4c35bce760d07e3f1f3d0b9cf/aspnetcore-runtime-3.1.10-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "bbeb4954590732063d1fbdf865818549"
SRC_URI[sha256sum] = "ef11a880d59b19f1df355b3c9c8b35ea1aa37e72d179850051cad963cb72358f"
