###################################################################################################
# Contains the URL and checksums to download version 5.0.17 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2023
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/b0a08e01-2992-45d1-9f93-3b9d538bb007/eb834b9711f525447d3178627983bc14/aspnetcore-runtime-5.0.17-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "b5d452d3c2466f27c8726cc56a54db70"
SRC_URI[sha256sum] = "37ce1896bf1f017b8d6060790489c6dc8ade957f7e0716bf938214551eead08d"

