###################################################################################################
# Contains the URL and checksums to download version 3.1.3 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/d5c6e9d7-25b9-47ac-9d67-35ac65211ad3/c8f4ccd0dc02ca8229ba43ecbe84294b/aspnetcore-runtime-3.1.3-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "122bbe03e6e7e9bc033a8f4dbea1c213"
SRC_URI[sha256sum] = "9dab4863b0203bf7b6b59f3533e55f7dda3624fe209eef3199510e917df9da13"
