###################################################################################################
# Contains the URL and checksums to download version 6.0.2 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/93874c40-bd2d-4a7d-bbb5-716b161594c0/f698334222759b065f5da4e8915ae982/aspnetcore-runtime-6.0.2-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "a1379367bba7a9b4d829d1302c4edd37"
SRC_URI[sha256sum] = "c57cfb1a77c4b23c7353e46b7d759f9e7da24ffe051b84cc4d6643d272819fc5"

