###################################################################################################
# Contains the URL and checksums to download version 3.1.1 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/deeee432-fd3c-4dbc-bc06-cbf166cbcfb7/04747ae7a0ea63e01b6f932cccdcf837/aspnetcore-runtime-3.1.1-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "9b126c3ab71263aa86a8973241de8576"
SRC_URI[sha256sum] = "10079255bc31a7a6b57845f22ccae585e2275a48108e43103cd6c700d38f5435"
