###################################################################################################
# Contains the URL and checksums to download version 5.0.14 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/960844f6-f1ef-4bd1-808e-3c6d7bdfc961/edd9f3c40525812c4035129939e8be51/aspnetcore-runtime-5.0.14-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "e6b94cfa340656b0aa0f1b6d901fcf18"
SRC_URI[sha256sum] = "38cc7531b34dba5096c8d5ea6059630cc5b26f90bca71a2cfb449a77fa985e4e"
