###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/8b734651-326f-4eb4-8a75-da94e991a901/f404fe1e1a2e989cb2e7bde13a3a2be5/aspnetcore-runtime-3.0.0-preview8.19405.7-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "c634a0124d0a476fe3bef1643b907cfc"
SRC_URI[sha256sum] = "b7fdaf41a20a9bc1c861cfd0fbbc71a30e0d0ce2baa13bf7ad508e0a438ea0cb"


