###################################################################################################
# Contains the URL and checksums to download version 6.0.14 of the x86 64-bit ASP .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/092f7e69-2e23-40b3-8f36-628d25ac7109/4995e4e141b26ea049163af84592222c/aspnetcore-runtime-6.0.14-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "7b28314c770497434a68bdd3b05f6e77"
SRC_URI[sha256sum] = "721dc8e29892dcaaaab4bc7d2e8630a98d349f2d832855156f7b7898d1a55b07"
