###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/3e353b69-78d7-4223-86e9-77bd08c751a1/253e8781ea13f02cb25d64ac0119ceff/aspnetcore-runtime-7.0.1-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "a908a2a47709c19d1556ff6e00b33054"
SRC_URI[sha256sum] = "eddd0c0a68e2677aa0b9a9a10b623c734f6e2381566318ad930ff72036ae8c13"

