###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/61cb6649-f41f-4966-84ae-9ff673528054/9bbd07607c5a1af87354e1fa93c36a00/aspnetcore-runtime-7.0.0-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "ef17207ee429b297df15f1648e8aade6"
SRC_URI[sha256sum] = "5828b4c6f7ab2b7d3bf3e391d769303750f50e8615ace00ede112bccf9ed9ea1"

