###################################################################################################
# Contains the URL and checksums to download version 3.1.1 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/6e16157f-154d-408d-b0cf-da0b26bea28e/330abbc17b7963efde5d5bdb36cd8933/aspnetcore-runtime-3.1.1-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "d6862d6d7ff8bee09abb25d88c13ddfd"
SRC_URI[sha256sum] = "c0ca54f52c9ff6c65b8409327eece45cf2dd74b8bd8010a3fd29cf5c6a88cae1"
