###################################################################################################
# Contains the URL and checksums to download version 6.0.14 of the x86 64-bit ASP .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/265a56e6-bb98-4b17-948b-bf9884ee3bb3/e2a2587b9a964d155763b706dffaeb8b/dotnet-sdk-6.0.406-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "fb0313d724c69fb4a32a98529483c85d"
SRC_URI[sha256sum] = "adf66cd85cc023de2b60347f8773eaf1d2e07697ca73b035da9f0a3b1cee7021"
