###################################################################################################
# Contains the URL and checksums to download version 3.1.8 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/251cd0f7-2655-4f04-940d-6fb852c4389d/65f8897905e79ee9306be9428dad88fe/aspnetcore-runtime-3.1.8-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "ad97220b0369949bda5e1b903545f698"
SRC_URI[sha256sum] = "18003038318f7e82174ac1958c8b910f6af03782b841fc41b3d5504a1d398527"
