###################################################################################################
# Contains the URL and checksums to download version 3.1.0 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/8c839c0e-a5ae-4254-8d8b-c012528fe601/c147e26bad68f97eacc287a71e01331d/aspnetcore-runtime-3.1.0-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "aae1e1724be64af2c3d7e02cfa4c2cb1"
SRC_URI[sha256sum] = "8f51d6bd94e0eb84adb9d707c19832e98b4e94c2a09c6c9e76d8a8cc625834d6"

