###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/5cbf9f66-7945-43e2-9b7c-351f900e9893/2fcd48f3d4db99283ebdb46daf9bacec/aspnetcore-runtime-3.0.0-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "10a94b9ba71711fd8edcc6a67bb40f40"
SRC_URI[sha256sum] = "4f679474e7b35e0fa3adc366d4daa85f1dafc34d2c592efd91e4d53a7e4a6014"
