###################################################################################################
# Contains the URL and checksums to download version 6.0.11 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/e25f7ff2-9932-41dd-b549-5b4409b5a727/d00786aeabad50cd661e959a576f8777/aspnetcore-runtime-6.0.11-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "6d6e381872f8c5c0a75d82bec33851ef"
SRC_URI[sha256sum] = "b9960c5a343903e38ef84ee8ef00551330b7a64b3fb4d75d8cd2ddd29a23841e"
