###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/ea4b23b0-d7dc-4d39-8de4-d4c89e1f9551/bfe628fcb8f19d4c97c75d1217af1a8b/aspnetcore-runtime-3.0.0-preview6.19307.2-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "70ca6073de2264cf5189b7ae2da511b1"
SRC_URI[sha256sum] = "24c009363c072f6c76687ce686b4aa3d72b4eb5eaf1a3ceb85bdff6807719b28"

