###################################################################################################
# Contains the URL and checksums to download version 3.1.3 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/b68cde83-05c7-4421-ad9a-3e6f2cc53824/876dbfc9b4521d3ca89a226c6438ffc1/aspnetcore-runtime-3.1.3-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "c29c40acd1751cec7f7ecdc49eab68c2"
SRC_URI[sha256sum] = "467490cb72058017e557aa8c20c9c5f45d6f3f23d75c530cedb819dea2f7270d"

