###################################################################################################
# Contains the URL and checksums to download version 3.1.0 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/30915c37-fa5a-4930-b4e6-b4130e4596b2/38d531c10dc56950f17f3c604e9a2ebc/aspnetcore-runtime-3.1.0-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "0ede8e21eea224062718557e0639c568"
SRC_URI[sha256sum] = "152ff377482d234b06ed2db85fe437e1975008c5fe6722bc8a300bad6a4ac578"
