###################################################################################################
# Contains the URL and checksums to download version 3.0.1 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/57bf6ac3-1712-4b36-bfab-80b31d7ce21e/1ca71849902d73eb083bcc2c2f4d8f4f/aspnetcore-runtime-3.0.1-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "619096ecfbeb18903a28cdc1c40cd355"
SRC_URI[sha256sum] = "2529d9c5dc33acd8f957c7696dfe295a30e72dd4e025b21d07e17ad82fa455af"

