###################################################################################################
# Contains the URL and checksums to download version 6.0.0 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/3d49ea48-675e-4da9-87be-18efaa99d7f6/37807ed5012ba5e0511e08ad64d6a9a4/aspnetcore-runtime-6.0.0-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "3ffccdd3b2a63b328b2e9bde07d0228b"
SRC_URI[sha256sum] = "07dd14194e37c839a9580a212f9fd47131d443058f399177c3747b56fad35948"
