###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/0bff102b-7983-4947-be67-be740e168ec1/d4b2a3818f2849501710b6ee16a1e2be/aspnetcore-runtime-3.0.0-preview8.19405.7-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "5ae9754b95b08cea861b6ca191a310dc"
SRC_URI[sha256sum] = "50e81dab852bdf0d95ae6d5fe39860dff676282cd2fe4e3824d76230117be3eb"

