###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2023
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/712946ec-0b43-436c-abfb-3abab81f6cad/c83ba8df4dab39957ffa5e93604f0b32/aspnetcore-runtime-7.0.10-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "c2007835821ef61b1869bc923384b3ea"
SRC_URI[sha256sum] = "dbb93f1d326ffd1754eff6239ca9513432d272c6f99909a2080c71288cc6a274"
