###################################################################################################
# Contains the URL and checksums to download version 6.0.11 of the x86 64-bit ASP .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/0a17a9f6-7705-4b47-aead-c0b582cad317/158b62e5183281e416994d56ce81bc0c/aspnetcore-runtime-6.0.11-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "0ed77ed71ebf8890f0923083920ef2db"
SRC_URI[sha256sum] = "d499a4af84cc3f9947230392f10d5af5fda65a71e002554f2ea3cd4244538133"
