###################################################################################################
# Contains the URL and checksums to download version 6.0.21 of the x86 64-bit ASP .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2023
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/56d44b17-03c2-4d9e-bdbc-a598ca34fc01/8fcc1e19dfd3c86b09beb68460db6e85/aspnetcore-runtime-6.0.21-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "5f93d589e1c2ce37ed4bd4678ef79586"
SRC_URI[sha256sum] = "bc8cb0e3f37d08a9402119fb2f00d41f97678cad1b5ec65458ec8f489ee80e10"
