###################################################################################################
# Contains the URL and checksums to download version 5.0.17 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2023
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/a2b96f83-e22a-4fa6-a10e-709b3effac9a/0d6ade6c0ceebc8ef7dbf2b1a6d86f17/aspnetcore-runtime-5.0.17-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "b5ac25ef66461ee4678e81d5e7beed21"
SRC_URI[sha256sum] = "b9979c99d49bcebcbdfc1cf780a8336323dfdc5cd1c656dcb6e7aae66e12006c"
