###################################################################################################
# Contains the URL and checksums to download version 3.1.1 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/da60c9fc-c329-42d6-afaf-b8ef2bbadcf3/14655b5928319349e78da3327874592a/aspnetcore-runtime-3.1.1-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "2503ad22dc202c905a9e0b9d9cda6e46"
SRC_URI[sha256sum] = "78948786fb2893a78caf6662b1832877064c139006af37d79257017880372d9b"

