###################################################################################################
# Contains the URL and checksums to download version 7.0 of the x86 64-bit ASP .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/6f0e5e7f-cf41-4ece-a728-eab7894157cc/b043910ee98786617d99cef8e8914c23/aspnetcore-runtime-7.0.1-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "cc8899a19357666dcd65ec269d9adead"
SRC_URI[sha256sum] = "75a6025ec533f1f930e45185418e2212444bd3f34265759522fde170b40eefe1"
