###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/b0c44e05-b7a1-4221-94ec-a0c0d3a11eed/afc61567dd6db8f097e244871889458c/aspnetcore-runtime-3.0.0-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "953d1fcef81eba738ccf30589563ec59"
SRC_URI[sha256sum] = "8d28aa53f47e8b2ef5c39ddee75cc22527ace332c528bbe85da99bf1b4906b36"

