###################################################################################################
# Contains the URL and checksums to download version 7.0 of the x86 64-bit ASP .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2023
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/08af0433-9ec3-4604-9d1c-85e3922a4524/396b340b4ee38765d7462e2fc61a5e3c/aspnetcore-runtime-7.0.10-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "56167a0855c7c2854baca76a9027ac5d"
SRC_URI[sha256sum] = "314c59386320cecf6474315999bc859a6d81751dce3ffeae5765d90948f6dd67"
