###################################################################################################
# Contains the URL and checksums to download version 5.0.12 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/0d780521-07bf-4e3e-94d3-57168d50eff3/1c7c9b5dd51e4751c04af943c5263679/aspnetcore-runtime-5.0.12-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "ff9504c98e146cd291fd176fa2278f08"
SRC_URI[sha256sum] = "bb93c16eee1f46695d336b9eb0b9b376916d744fcf0f0d4fdabc6cc9a7f03dfb"

