###################################################################################################
# Contains the license type and checksums for the ASP .Net runtime packages.
# Copyright Sequent Logic 2022
###################################################################################################
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=9fc642ff452b28d62ab19b7eea50dfb9"
