###################################################################################################
# Contains the URL and checksums to download version 6.0.0 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/b86e414a-929a-42a5-ba18-45ad2ebe292f/3617879c51e87fe70073006bf2d60386/aspnetcore-runtime-6.0.0-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "6c2b230119b308236382e117eeba4128"
SRC_URI[sha256sum] = "a053004fd57b7e92fb971845a88e05054489028e98ca093a9f5ebae382a13958"

