###################################################################################################
# Contains the URL and checksums to download version 6.0.21 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2023
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/1f8d7d02-581b-42f8-b74a-bf523099ab5c/29da812824f1a8cdfbe452aa5bc0ebc3/aspnetcore-runtime-6.0.21-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "715cd86887eb7d6c42008a472b04cfd0"
SRC_URI[sha256sum] = "29ca9fb2308d5c927c9673c96836b144e6f0ea52041f7258ed14eb8f42dc2b15"
