###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/0040c5cc-ea1f-4d64-b9f3-9b4adc3811b6/fab5141cf1850d520eb2bc00bfa80183/aspnetcore-runtime-3.0.0-preview6.19307.2-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "fec6fdf295753534e3d65a745f7a041c"
SRC_URI[sha256sum] = "5a2c466d13fe2147a817621440981f8fe7cc3a79e05d3bdfd2fd2685ad2d1216"

