###################################################################################################
# Contains the URL and checksums to download version 5.0.12 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/ad0a54ca-4b88-4762-a790-aebeaba6b9e7/0f796fb90696d078046d90d8a05c027e/aspnetcore-runtime-5.0.12-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "bd06fe086e9e85997a2e192385e187e9"
SRC_URI[sha256sum] = "ea97d8c86178c3d29fafc485013267ac3801cdd275ac7653b3b95d087ff5e530"
