###################################################################################################
# Contains the URL and checksums to download version 5.0.0 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/4f20eb4f-886c-44ba-aff4-c80356da3a53/e2933e72c3fdd65dd242f1260877a7f6/aspnetcore-runtime-5.0.0-rc.1.20451.17-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "5ac85e7de092bdfa6c431e02e4ace7fd"
SRC_URI[sha256sum] = "a8fb11cf5924c084d560b4dfb66003241b5075fbe2958006215b6b85ca490050"

