###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/e3d97ec5-f36c-45e5-bd0f-c58b0c468ec2/0b97b0983d826f854d9328165393bf1e/aspnetcore-runtime-7.0.1-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "4246636fa2dc2d83b6110e9b62376c27"
SRC_URI[sha256sum] = "b9fb623b50050e50a802fe744a71c9f99ddc5906ce209343a56800e8f3b21cef"
