###################################################################################################
# Contains the URL and checksums to download version 3.1.8 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/401a2d7e-e959-4517-93fb-94b9f3b43123/0eca99d7a04ecd47cc6ccfab78fcfdaa/aspnetcore-runtime-5.0.0-rc.1.20451.17-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "d593ba5718f2784b73857e5b1cd5e265"
SRC_URI[sha256sum] = "58f93e62db2197b4a30e6e39501afbb41af0076ef6a7881a4d0a26a9673f40c7"
