###################################################################################################
# Contains the URL and checksums to download version 6.0.12 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/8072e219-57e4-48c3-b138-2b4067844ab2/b0712ad06fd0740963bf4ba2eff7f5ea/aspnetcore-runtime-6.0.12-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "9771b7e57f31e35be5e990338e87bc6f"
SRC_URI[sha256sum] = "0090d031615b7d49855186cff7e4cbc99636ba664880780f84ce0d5ce25e4b0b"
