###################################################################################################
# Contains the URL and checksums to download version 6.0.2 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/83695c9b-c954-459e-b9bf-2f1ac269e34e/1316ff4a6fe4c6916e7ecb3623d67cee/aspnetcore-runtime-6.0.8-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "d9828029ded9729150033a47be630d49"
SRC_URI[sha256sum] = "8a8d7ebfd2a6a806e57b6bfa1fd71b99a789c947c66c30c081824b1a00123c78"
