###################################################################################################
# Contains the URL and checksums to download version 3.1.8 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/ff9a5b2e-704b-4ff2-bf2f-4bac619915af/e771f72b10ad5160ab5f3d70c287e948/aspnetcore-runtime-5.0.0-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "371236e056fa710895a827bd6c68a0c1"
SRC_URI[sha256sum] = "de6ab398bd0c7757c505a25d6eaf560d8f4b3c3a66b0462d6e8afff97ac5e2d1"
