###################################################################################################
# Contains the URL and checksums to download version 3.1.3 of the x86 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/933b0cb8-3494-4ca4-8c9e-1bcfd3568ab0/8704eef073efdfecdaaad4a18beb05ac/aspnetcore-runtime-3.1.9-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "b7ad7d0e494f267d7caeee80c595f216"
SRC_URI[sha256sum] = "b47a882277d4ef42d3cfebbd1f334559b8345fe8a8b05e2a7d83a37ffe5f775e"
