###################################################################################################
# Contains the URL and checksums to download version 5.0.14 of the ARM ASP .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/c7a910e3-4d1d-4d14-a4c1-cd95c75edad3/7fb356b6848053fa8178b3451740c6b2/aspnetcore-runtime-5.0.14-linux-arm.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "a3ea0fb7aeba564acce35613efed824e"
SRC_URI[sha256sum] = "131b99bca47e0ff2ac0aaa95b258dd747973c3002dad3a162326da5c532e25d5"

