###################################################################################################
# Contains the URL and checksums to download version 3.0.1 of the ARM 64-bit ASP .Net Core runtime
# from Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/e02ed469-29e8-479e-a0d3-7b6f9946175b/05f2adcc8fcd4dd09cd7fca69ba3b325/aspnetcore-runtime-3.0.1-linux-arm64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "4acae847a6b0bf558c888e5971dc336c"
SRC_URI[sha256sum] = "3c1d1f5d9f80cf0cc3948f19be1c3eca77b3874e14fee79e9fca45fef97b150f"
