###################################################################################################
# Contains the URL and checksums to download version 16.0.20419.1 of the 64-bit Visual Studio
# debugger from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://vsdebugger.azureedge.net/vsdbg-16-0-20419-1/vsdbg-linux-x64.zip;subdir=vsdbg-${PV}"

SRC_URI[md5sum] = "0fe8523b5c637b0de6a890d78c171e87"
SRC_URI[sha256sum] = "3cfb4b1fba86022926062c2e2ff77949912997f70938297fa558a90c0cb433cc"

