###################################################################################################
# Contains the URL and checksums to download version 16.0.20419.1 of the ARM Visual Studio
# debugger from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://vsdebugger.azureedge.net/vsdbg-16-0-20419-1/vsdbg-linux-arm.zip;subdir=vsdbg-${PV}"

SRC_URI[md5sum] = "72bcbeb65c78c1aa6af105ccc0128b3e"
SRC_URI[sha256sum] = "f0083959e34b6706fcabc2b2bade1ab3c90e3d542cd67d3d7a01fb251837ce56"

