###################################################################################################
# Contains the license type and checksums for Microsoft's Visual Studio Debugger.
# Copyright Richard Dunkley 2018
###################################################################################################
LICENSE = "Microsoft_Software_License"
LIC_FILES_CHKSUM = "file://license.txt;md5=b84c3bcd1eb089d7eff9fb20768b47a3"

