###################################################################################################
# Contains the URL and checksums to download version 15.7.20426.1 of the 64-bit Visual Studio
# debugger from Microsoft.
# Copyright Richard Dunkley 2018
###################################################################################################
SRC_URI = "https://vsdebugger.azureedge.net/vsdbg-15-7-20425-2/vsdbg-linux-x64.zip;subdir=vsdbg-${PV}"

SRC_URI[md5sum] = "e8ef7f5c5307ffd086657a478c46b919"
SRC_URI[sha256sum] = "c2f051aefc588cb65e72e25b9454a182c62f20ddfe7e25a35b57383ed2c40f35"

