###################################################################################################
# Contains the URL and checksums to download version 15.7.20426.1 of the ARM Visual Studio
# debugger from Microsoft.
# Copyright Richard Dunkley 2018
###################################################################################################
SRC_URI = "https://vsdebugger.azureedge.net/vsdbg-15-7-20425-2/vsdbg-linux-arm.zip;subdir=vsdbg-${PV}"

SRC_URI[md5sum] = "7d56be537a8d061f56d6012799cc4b80"
SRC_URI[sha256sum] = "14049dd1100f67cf892df540bbea79272afaf90fe3db3dd67a5730d7a965eea6"

