###################################################################################################
# Contains the URL and checksums to download version 7.0 of the x86 64-bit .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/0b330412-234f-48c5-957c-c3c8c854a400/8d9a07cc153fd16a828d78c136b47e6f/dotnet-runtime-7.0.1-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "61d0a5d7532d480a5214c8593bd2b744"
SRC_URI[sha256sum] = "b82436603a60ec2e801d3f0c734f1b62313c7b6bd132151aa4e6b0585047cb7a"
