###################################################################################################
# Contains the URL and checksums to download version 6.0.11 of the x86 64-bit .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/367108bb-8782-4f0b-839d-c98191b7729a/94185f91ef33890816a5846a374b74b7/dotnet-runtime-6.0.11-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "8f0d94eb2fc39f530a38d498bd6d44a0"
SRC_URI[sha256sum] = "8b5b933de46d7d885ce99f4e5b49204ab46dd1c0eac9c976ef39558e20a490bf"
