###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/177a9aa3-d714-4c14-8421-8ba58eaad7fa/cc80f512ca48c6b57ddb923e3505c7b6/dotnet-runtime-3.0.0-preview8-28405-07-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "2d7d62c442e050459e125338f1001199"
SRC_URI[sha256sum] = "7f628fb8fbfd69500df3b10541c0548e601defec3442726f571523f166781bee"

