###################################################################################################
# Contains the URL and checksums to download version 5.0.0 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/cac4993a-0f79-43c6-baf9-f688867a37bf/adf0935ca2082cd05d3f00adc04d1848/dotnet-runtime-5.0.0-rc.1.20451.14-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "08a15980212c4e275f1e08b854e38020"
SRC_URI[sha256sum] = "21d5b6b5f94078b32208245f991a9b460c87f76f1883918b08577f0132541134"
