###################################################################################################
# Contains the URL and checksums to download version 2.2.6 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/9f21e352-9d2c-4e3b-af45-915da89158db/0e8a7ea83cc08d4bcf417a927a36ed6f/dotnet-runtime-2.2.6-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "94d6733e662cbcde1efb28eec03b5499"
SRC_URI[sha256sum] = "e30d4568c62d747b030e3c74f3d528ecb8d5c90e844e506bc0e3fcbce52b8cb1"

