###################################################################################################
# Contains the license type and checksums for the .Net Core runtime packages.
# Copyright Richard Dunkley 2019
###################################################################################################
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=9fc642ff452b28d62ab19b7eea50dfb9"
