###################################################################################################
# Contains the URL and checksums to download version 2.1.3 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2018
###################################################################################################
SRC_URI = "https://download.microsoft.com/download/6/E/B/6EBD972D-2E2F-41EB-9668-F73F5FDDC09C/dotnet-runtime-2.1.3-linux-arm64.tar.gz"

SRC_URI[md5sum] = "f93ccf7d899cbd304141e31021b8eec8"
SRC_URI[sha256sum] = "771904d72f06eb816e5a4adbaa76c4352c097fbf5ed7dee9e4059e776278223a"

