###################################################################################################
# Contains the URL and checksums to download version 3.1.1 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/c1d419e7-4312-4464-b272-27bee7676560/22e7bb584ff56f3089c85d98b21c0445/dotnet-runtime-3.1.3-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "6dc0dace2f81826cc28390e4d502077a"
SRC_URI[sha256sum] = "e0a9d4a206caece4de6d39e7d95245b2357ae69280b1f3e1b19fb9de8e1c1174"
