###################################################################################################
# Contains the URL and checksums to download version 3.1.8 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/3f331a87-d2e9-46c1-b7ef-369f8540e966/2e534214982575ee3c79a9ce9f9a4483/dotnet-runtime-3.1.8-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "c41e0c8dd065970fb633d4f4dd8e2643"
SRC_URI[sha256sum] = "3b881ec6c721a755badc94d1a8dbb04132e38783cc673b6cb2e99438c571a181"
