###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/3873ce54-438c-43bd-871b-0472e4d5462b/01353d2e8c4289bb344d935c4bf4de3e/dotnet-runtime-3.0.0-preview8-28405-07-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "fc7eb2bac762898da5af53f6b9f82fe0"
SRC_URI[sha256sum] = "7aa76e1afeee69d5c007b2383b6b0f0fa16b3a87031979c242bb212856505a15"

