###################################################################################################
# Contains the URL and checksums to download version 6.0.0 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/dcd635a9-6caf-4958-b3df-01e1c204ca1e/b201804d05de9573a8b454bccac56482/dotnet-runtime-6.0.0-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "7e4abb26f76671abd739cf756a4fcd3d"
SRC_URI[sha256sum] = "b170f6a98dbd4de8708a0cad5da7b7de970a02bbc3c34fb15f8e811195a00e9b"
