###################################################################################################
# Contains the URL and checksums to download version 5.0.14 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/a33a7fce-f5ec-4155-8b47-db5f534616b5/009a2daa585e5168fffa041e0db11c58/dotnet-runtime-5.0.14-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "16b5b1a1ce741a75c5c4933aaec75005"
SRC_URI[sha256sum] = "acb855120e6da13ca348cd3125e91ef0aa6460090da2faad7934303c612c6a87"
