###################################################################################################
# Contains the URL and checksums to download version 6.0.2 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/8c34904d-88e8-4dc1-af91-fc1e5cb64a25/6ae9f205eb54fdd03e12e04daa43c015/dotnet-runtime-6.0.2-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "0c6590045b8b97501e16a5a893ec2c22"
SRC_URI[sha256sum] = "2e17eb4bf81f67705cc742d3077af65e8c2fa3aee3fd39b5740918c7b31ec3cb"
