###################################################################################################
# Contains the URL and checksums to download version 3.1.1 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/7c1177f6-feb9-4404-a795-adb77e78b9ab/d3ca4e135e1af71bea28623774f8df27/dotnet-runtime-3.1.9-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "fe06dd1333839be30054f710d12f8eb8"
SRC_URI[sha256sum] = "1d496af340e0bf4b1c1a697b8c1645eacbd0dbacb1bb2986226ac3a089d5633d"
