###################################################################################################
# Contains the URL and checksums to download version 2.2.5 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/87521bd8-1522-4141-9532-91d580292c42/59116d9f6ebced4fdc8b76b9e3bbabbf/dotnet-runtime-2.2.5-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "541f6642765cd76a33c95c748b84d685"
SRC_URI[sha256sum] = "28ec99093dc19bd97f63af149023a12ada891211c8ccb2fb8510a8c06127dde0"


