###################################################################################################
# Contains the URL and checksums to download version 2.2.8 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/428aaa32-f66c-4847-b845-aa21f90504e4/1cf033db866414997140c2672bd75069/dotnet-runtime-2.2.8-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "58126d47e03bd3cc1a3e4c7ae71cc3de"
SRC_URI[sha256sum] = "a2bc63763574413364369f0e5cc658d24ac1da3941781537c7dc3385ae89d38d"
