###################################################################################################
# Contains the URL and checksums to download version 2.2.2 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/a24ca9ae-7966-4a9e-9838-cc57d6639248/099c000dc8ee58702846702e9b010ad1/dotnet-runtime-2.2.2-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "44f0b70090283eb35720bcf1f18e1e04"
SRC_URI[sha256sum] = "38d0cf015ab098a5d5fcee0e262d084d2bdfdd88c9abdf442b065b7a0d6b6cc8"

