###################################################################################################
# Contains the URL and checksums to download version 2.2.6 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/f5e04830-50fc-435c-8bb5-fcd4629da944/8aa7cce5c3fcb6a7db180b923d3574ef/dotnet-runtime-2.2.6-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "626897080d9b5bc90319086df94c54ce"
SRC_URI[sha256sum] = "48d58ac6ff958ec7155befe76f83e276aceff50c4a7d1f578444a9a40720e412"

