###################################################################################################
# Contains the URL and checksums to download version 5.0.12 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/7c342ad2-2dae-471b-ae46-c0c820321c1f/a480ad8ca0bc826a48c9b1e56efd972b/dotnet-runtime-5.0.12-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "9d6e384ef5f00f6ee5e7562696415486"
SRC_URI[sha256sum] = "3f3848e75f78339a65d2423cbbed0f37d411dd1c6d13cedf606e20ab5d6e1936"

