###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/f15ad9ab-7bd2-4ff5-87b6-b1a08f062ea2/6fdd314c16c17ba22934cd0ac6b4d343/dotnet-runtime-3.0.0-preview5-27626-15-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "6bf364855672f3b48ff3a1c252af8944"
SRC_URI[sha256sum] = "a2c6135013a99d425b09a372f5500cad01fbffaf6461a53ae1616482f17dc78c"

