###################################################################################################
# Contains the URL and checksums to download version 3.1.1 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/c11e9248-404f-4e5b-bd99-175079419d6f/83902a43e06f9fb4e45a4c6a6d5afc0b/dotnet-runtime-3.1.3-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "4a0d3163c5f85611efdf0fc55cbc4556"
SRC_URI[sha256sum] = "2c7cd1ced5d2c5aa2b63d2980cba0d62f8bb07ce9ae18e692cfc3c8c5989bef9"
