###################################################################################################
# Contains the URL and checksums to download version 2.2.7 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/f5e04830-50fc-435c-8bb5-fcd4629da944/8aa7cce5c3fcb6a7db180b923d3574ef/dotnet-runtime-2.2.7-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "3cc64cea798fe5443102623da22fea9a"
SRC_URI[sha256sum] = "3b161863bd455e4755c7af3267a6b6e3a45b56b3ad8589bd202865eedf74b3a8"

