###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/f6f57f07-c407-4dec-a11e-7c521b842dff/edea09e548e1b673ccca1b2c685b0b12/dotnet-runtime-3.0.0-preview6-27804-01-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "47eeaeeb1e3d472dcdb78669b172b212"
SRC_URI[sha256sum] = "cc323075d9952f17a947066b8b82b5313044021c0e19d5257ae0469f0dec8ef7"

