###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/f274b190-2f0b-4616-a446-7090b55dd80c/1b652d6a8a50a8a6f0efc098a6e5e6dd/dotnet-runtime-3.0.0-preview6-27804-01-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "8a138a86cb2e0b8d5c7b7c4f5be2addb"
SRC_URI[sha256sum] = "c0f789d348c05bae35b4a5a8d2a417c733afae747c544910cdcb5c32c4c93316"


