###################################################################################################
# Contains the URL and checksums to download version 3.1.0 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/60d21925-7f8f-4004-9afe-aebd041d2d4a/0db2946738642d7f88f71f7800522e8c/dotnet-runtime-3.1.0-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "296aceb99470edf54a9eb4b8b6ada534"
SRC_URI[sha256sum] = "934739f3a3e08f7d14756183bff343641b00768897448dc72b2bb31c529d87ce"
