###################################################################################################
# Contains the URL and checksums to download version 2.1.5 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2018
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/8b757bfd-de6c-4c72-8d73-abfa6d7bae35/54a47a57feccb5277e0973e17142caa6/dotnet-runtime-2.1.5-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "5e573af9665c7030f1815a7639dd9e6a"
SRC_URI[sha256sum] = "b6dee5febd8a912de89b432100ba2c717e855766ede3ec15ba0e736541070c07"

