###################################################################################################
# Contains the URL and checksums to download version 6.0.11 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/b02be36b-8470-4b81-8254-1f957ce8f397/fd6aa0da17fc51c1b57b2d96aa792c1a/dotnet-runtime-6.0.11-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "24dda20f58e2deabe4199d0294a95fe5"
SRC_URI[sha256sum] = "526dfd1ba17ff880c7fc575af6792f01d19b6fb9f98253e673752430d15bc71a"

