###################################################################################################
# Contains the URL and checksums to download version 5.0.14 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/86fc75ca-8ba0-4d49-b505-3a7e10b2e26d/dde7cd87f4ba2f07c5249e779c0fc0ff/dotnet-runtime-5.0.14-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "9459a93cfd77bd514139d8faf9fb01a9"
SRC_URI[sha256sum] = "999d830da0765d5c7a5ffb2534ea0c2d34e29fb586df82c751cb902e0dbc54f1"

