###################################################################################################
# Contains the URL and checksums to download version 3.0.1 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/85917a71-f8c5-4735-8a6b-ef9082cc954a/9b2b52dc5cd003f02e689611f40ccc9a/dotnet-runtime-3.0.1-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "8292512cc5635f2d863a1dac53042e1f"
SRC_URI[sha256sum] = "608349056e6a78ab51b533fc7fdd3759d753eacbbec7b4079b9616bf22192f87"
