###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/6b9171b7-40cd-434f-89f4-d5cb4a7b2611/ff32fed2bbffab1661914d469afaea85/dotnet-runtime-7.0.1-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "c0e46efd77b690a8ac6ba7603a08b870"
SRC_URI[sha256sum] = "caf0ea9fa38d26eeda38081bf62d5be5ca00e7202949eb3a599ce2a0dc3a5e9c"
