###################################################################################################
# Contains the URL and checksums to download version 2.1.3 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2018
###################################################################################################
SRC_URI = "https://download.microsoft.com/download/6/E/B/6EBD972D-2E2F-41EB-9668-F73F5FDDC09C/dotnet-runtime-2.1.3-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "59215d7b1e12b55d426630598306f9cc"
SRC_URI[sha256sum] = "cbdc689bff4dc01cb89e792d34a296bf9971f251719b6d60bbe5c5caeda846c7"

