###################################################################################################
# Contains the URL and checksums to download version 2.1.2 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2018
###################################################################################################
SRC_URI = "https://download.microsoft.com/download/1/f/7/1f7755c5-934d-4638-b89f-1f4ffa5afe89/dotnet-runtime-2.1.2-linux-arm64.tar.gz"

SRC_URI[md5sum] = "2418db1d7493b0e6945c9bcc369adf2f"
SRC_URI[sha256sum] = "09c4b9c369c7f98066ba493a36a5c256eb102031739bec4862b58299590b5a18"

