###################################################################################################
# Contains the URL and checksums to download version 6.0.12 of the x86 64-bit .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/7d543956-0b80-4c08-910e-c8c388f5fab8/01d45a3686e72f70be51b3f98569c6b1/dotnet-runtime-6.0.12-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "709c654f2aa44313d2ec785668f98f9d"
SRC_URI[sha256sum] = "2ad75c53eea6ad561c22efc53f7a78db0ed82d8ca3a1e1d39d0c97b41348bdba"
