###################################################################################################
# Contains the license type and checksums for the .Net Core runtime packages.
# Copyright Richard Dunkley 2018
###################################################################################################
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=42b611e7375c06a28601953626ab16cb"
