###################################################################################################
# Contains the URL and checksums to download version 3.1.10 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/8261839b-2b61-4c49-a3e4-90b32f25bf50/12ff8ed47c32c199c04066eb07647f4e/dotnet-runtime-3.1.10-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "fa6c57c0d72d9724f634b5949979eb44"
SRC_URI[sha256sum] = "75e7bea2edfa8e8996f9faad2816370e666a1d2c903a6ee3168cca6fccce1c77"
