###################################################################################################
# Contains the URL and checksums to download version 2.1.2 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2018
###################################################################################################
SRC_URI = "https://download.microsoft.com/download/1/f/7/1f7755c5-934d-4638-b89f-1f4ffa5afe89/dotnet-runtime-2.1.2-linux-x64.tar.gz"

SRC_URI[md5sum] = "d848fb6048a18f037cc89c4dcdc02fef"
SRC_URI[sha256sum] = "0d0db92d1d4779ad28562ca445acd3701e61bcef957ae3dbdcc97a7c0e8f10c5"

