###################################################################################################
# Contains the URL and checksums to download version 3.1.8 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/e4e47a0a-132e-416a-b8eb-f3373ad189d9/43af4412e27696c3c16e50f496f6c7af/dotnet-runtime-3.1.8-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "c12f3c0964df3a9539d9d4b525b1c371"
SRC_URI[sha256sum] = "c50800e02cea23609ec6a009b1fbfe6b1f7ec4634c54bee089f918fca8fe2323"
