###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/779c214c-4898-4dbb-bc1c-0cea689a52ed/a8dc33d07be2bd14a5d581c08ebed653/dotnet-runtime-3.0.0-preview5-27626-15-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "2218a7499a15807534cdd2ff945886d2"
SRC_URI[sha256sum] = "a6acd4c81db46dc084c4a930bebf61bafbb93e592d5f35e2a37e3ec3c04b5a99"


