###################################################################################################
# Contains the URL and checksums to download version 2.1.5 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2018
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/4d555219-1f04-47c6-90e5-8b3ff8989b9c/0798763e6e4b98a62846116f997d046e/dotnet-runtime-2.1.5-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "6103c752156e4f4c87efb6ac254d41f2"
SRC_URI[sha256sum] = "05e22fcf0cb7e5e011e3937e2454aa5abadf9811092442d64ea07c4121fbfdbf"

