###################################################################################################
# Contains the URL and checksums to download version 6.0.11 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/8cb9b9c2-8eff-4c6c-bc28-f2c5a20b3f2d/1a495fde9c6814ca12e415328298a8c1/dotnet-runtime-6.0.12-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "344ade83008f8fa6aa787ca5bab28f75"
SRC_URI[sha256sum] = "781ebeac6351ecde243427b6cd5e9ccf5687958cb3a8bd659cd568eb3e6194d6"
