###################################################################################################
# Contains the URL and checksums to download version 5.0.12 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2021
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/2ca66adb-937e-44f0-9a80-8ee752917e7a/37c2e836710260ce00783fe1c0cb031d/dotnet-runtime-5.0.12-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "39c068dce94ba8cfba081c819987e24f"
SRC_URI[sha256sum] = "a290a2faa53b96d9000b5cf5347b3dac0d7318c40bd9f8f3c01584dbd137ef69"
