###################################################################################################
# Contains the URL and checksums to download version 2.1.2 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2018
###################################################################################################
SRC_URI = "https://download.microsoft.com/download/1/f/7/1f7755c5-934d-4638-b89f-1f4ffa5afe89/dotnet-runtime-2.1.2-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "688990b60859510832fca0512cc0ce31"
SRC_URI[sha256sum] = "bdbb9739092098c1e572bbdcc9799bdfb17de75fbf7f4e72898dbf63d424e14f"

