###################################################################################################
# Contains the URL and checksums to download version 6.0.8 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/3bdc231e-36c3-4bc9-85d0-c1889b17b1af/ec691544aec785d52417173ba7c17359/dotnet-runtime-6.0.8-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "acbb71b1d855ca511f0aaec5cc6b5206"
SRC_URI[sha256sum] = "b94ddeb26bb02819ef413c15234d0481e1a39ad9836b7cfaebb7cab078fcba6a"
