###################################################################################################
# Contains the URL and checksums to download version 3.1.10 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/9ca38d86-ce96-4647-8f27-a5807ac42d6a/081194806997d3152be461259cb0bdd2/dotnet-runtime-3.1.10-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "0c2b7147cdb7d2224c9819fd42c93f5b"
SRC_URI[sha256sum] = "991183e5551037d76f71910059e3e0b74e0806dfdbcf068e0c15cb46c0ae3349"
