###################################################################################################
# Contains the URL and checksums to download version 6.0.8 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/866ce4df-8aaa-417d-ad81-26131a2b8734/7ba8391188bc194156ee7d82f494ee00/dotnet-runtime-6.0.8-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "e63d7af97b027a661d4bb1d575a4f302"
SRC_URI[sha256sum] = "3ca0cc3475e845afea3adcff0b5faa28c293fb9803a812280619453a6f3984ca"

