###################################################################################################
# Contains the URL and checksums to download version 3.0.1 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/30ab052d-dbb6-4bce-8a44-a831034589ed/7ffaad695afb7ccd778b0d3fc1c89f50/dotnet-runtime-3.0.1-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "78504efc17be36c6489202ed1f54ea99"
SRC_URI[sha256sum] = "a677b829f58574b8fd5c29526c83615ddbff1f42810b01cb1a6b4bface8081dc"
