###################################################################################################
# Contains the URL and checksums to download version 3.0.1 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/6ff3b8af-4b33-47e6-bc11-73f85e0d2f56/bbb1282d7f16998eaeecd3ca258faf39/dotnet-runtime-3.0.1-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "3e5123829e32d46ecbc44b5d7323b85a"
SRC_URI[sha256sum] = "d14934dfc3ffd11461b213b14b744d148623336be8144ddf0ac42d6bddd1c110"
