###################################################################################################
# Contains the URL and checksums to download version 2.1.5 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2018
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/05a71d80-3e59-4f1f-8298-2697013e261c/be191f2f4f4db74c29030008ed3632f0/dotnet-runtime-2.1.5-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "95ad580530d3866befd98826973f8412"
SRC_URI[sha256sum] = "2962adbe0f52dc072e07f083ada37e5441a1981970196364612322f825c579d1"

