###################################################################################################
# Contains the URL and checksums to download version 5.0.0 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/9612ffe7-7091-4f23-843a-ea44698423df/9dc85938df3f46529273fd23f9b63e6a/dotnet-runtime-5.0.4-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "A4F000F63201BA3E894B9FC550C650B2"
SRC_URI[sha256sum] = "B04B23D12FDDF2123B4A79896DBE0726A4F36A8143AA91971FE512C99EA7323B"
