###################################################################################################
# Contains the URL and checksums to download version 6.0.2 of the x86 64-bit .Net runtime
# from Microsoft.
# Copyright Richard Dunkley 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/28029b9e-2851-4224-b781-13f2bfa8b975/4a3d5684cb104f6efdaef10d7978872e/dotnet-runtime-6.0.2-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "4c1caed980a73745b4ae66d2c5cbcc80"
SRC_URI[sha256sum] = "f70cb7d955aabff1fa9c05dbb4710516bee22e24f0280dbe75f24fb40ab69e1f"
