###################################################################################################
# Contains the URL and checksums to download version 5.0.17 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/6690730f-cf10-40f1-9d4d-4c0d002f22d0/e117133858f190c169873200b8d7b9d7/dotnet-runtime-5.0.17-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "19f823184b610e10b3095c1727a858e7"
SRC_URI[sha256sum] = "1894cf47827a4be9cb10e4405c6f99f162258ab0fc3c1cb3286928f4bc66caae"

