###################################################################################################
# Contains the URL and checksums to download version 6.0.11 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/cbcfbaa2-781b-4782-9994-9a9289ca724d/bc2fe2ee1a1842ea6d1151e5e0a410f9/dotnet-runtime-6.0.12-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "fc2e54af43e0a5738b7e709e61f18742"
SRC_URI[sha256sum] = "a6a77d132ddd2dc61a32674f68b918a1f4e59e5d7417ef5fff6df067d2f5f437"

