###################################################################################################
# Contains the URL and checksums to download version 7.0 of the x86 64-bit .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/d4b0a69b-29cd-40ef-9e95-a8d16f0ff346/5844add76ae3917af9efd59d95e3cbd4/dotnet-runtime-7.0.0-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "2fcc8983e601813ac6b50addc911308e"
SRC_URI[sha256sum] = "47538f598b5c60a51a1bfa643eae040b8e3832de1c2c2dcb1d3f2da6c7c4d76f"
