###################################################################################################
# Contains the URL and checksums to download version 3.1.10 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/be90bd1a-a314-4c87-8b90-7ac7681beea9/2297d87631c13074bb85abed61f8138d/dotnet-runtime-3.1.10-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "d611d776e9ba011941de3e2a70905f02"
SRC_URI[sha256sum] = "24e90af561d79154b6021d1d58bbf484c23d100269fa128e6d8225cd96d11fd9"

