###################################################################################################
# Contains the URL and checksums to download version 5.0.0 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/367623bd-affb-47ea-af65-466d6c002537/bae126bda0f016d1284402e73ab7d333/dotnet-runtime-5.0.0-rc.1.20451.14-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "dc252aec333747ae4e8257144372b18e"
SRC_URI[sha256sum] = "750801691e173af32e6f0fdbef6b353a5ac9cfd1abad6a81cf008d8a992220c5"

