###################################################################################################
# Contains the URL and checksums to download version 2.2.6 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/428aaa32-f66c-4847-b845-aa21f90504e4/1cf033db866414997140c2672bd75069/dotnet-runtime-2.2.6-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "878daf24d0136c69650e70c05e8c8816"
SRC_URI[sha256sum] = "a4f2e63471c296b7b173105a2c1d5feb95b81e0a8131f73aeecc00440fa5f544"


