###################################################################################################
# Contains the URL and checksums to download version 5.0.17 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/bf63c6b3-686f-42c1-bc6c-7d4fa5aa419c/cf21a114adde9ecbc66f17a693562c4f/dotnet-runtime-5.0.17-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "cf026951320b2f79708236dc42aff18e"
SRC_URI[sha256sum] = "ce1767be949f2126d0fa2bf2f5d28fdb7e3d130c2faa0881bc24a805e379ce76"
