###################################################################################################
# Contains the URL and checksums to download version 2.2.7 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/428aaa32-f66c-4847-b845-aa21f90504e4/1cf033db866414997140c2672bd75069/dotnet-runtime-2.2.7-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "db514d2071e0aadd807600a1b429e066"
SRC_URI[sha256sum] = "ec199e4a6f78ed368d7947135bd0e3f50a862d3815aa3ac952f4052bdfb11a28"


