###################################################################################################
# Contains the URL and checksums to download version 6.0.8 of the x86 64-bit .Net runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/5596ef6f-a174-4fba-aef1-99173e3f3c67/77edd755d605688885ca7114bc4f9ae9/dotnet-runtime-6.0.8-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "3d7159c502876068cebdc82a71e6b48d"
SRC_URI[sha256sum] = "be20edcb435e3505f661b01a0d363378f9e067fdd05e21b177817f072d43b2dd"
