###################################################################################################
# Contains the URL and checksums to download version 3.1.1 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/fb8a9fd4-c015-4c0e-a478-6da0b590bc39/d831b206c30e0aa23501b4a210dec9b1/dotnet-runtime-3.1.9-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "af60b81fc22e841fb201bca638f4f522"
SRC_URI[sha256sum] = "72417009bb23a7eaba88af4844d9e2aec6ce3ed8cdb5c14480c861fd417aaac5"
