###################################################################################################
# Contains the URL and checksums to download version 3.1.1 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/aec14e02-5c01-4447-b3f4-fa205b7c0603/7beea31e0c9faa20f5d692537cde54a5/dotnet-runtime-3.1.3-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "6411378b4ae4608c4a561f0efdcd33ee"
SRC_URI[sha256sum] = "72fbe81a7fb789914be83c0f70c22826137d30183984bc22974b8fc1e1876b5a"

