###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/038c1cc9-fcd5-4a0e-9547-acab08b0a4ee/c56e6ec6012bc6e9f52897166d543872/dotnet-runtime-7.0.1-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "8ff4f6434c9981fecf1c0b4e5641ba1c"
SRC_URI[sha256sum] = "837634b10e1194709a7ea1b888997de00bfea902e775256d163f8cb6618aa445"

