###################################################################################################
# Contains the URL and checksums to download version 5.0.17 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/e77438f6-865f-45e0-9a52-3e4b04aa609f/024a880ed4bfbfd3b9f222fec0b6aaff/dotnet-runtime-5.0.17-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "4ba46fd1b5a343d2089193a50331e0a1"
SRC_URI[sha256sum] = "12b44025aabf3d28242c47f84dd14237ad7f496715be55a7c5afd0fb34f66c8b"
