###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/0c5e013b-fa57-44dc-85bf-746885181278/58647e532fcc3a45209c13cdfbf30c74/dotnet-runtime-3.0.0-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "842ad6627001df9c81b186b1d4198000"
SRC_URI[sha256sum] = "0ef1e439d31047590792f6f375fe53a27492ed6d8233dbf16da094f0561cea41"


