###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/a5ff9cbb-d558-49d1-9fd2-410cb1c8b095/a940644f4133b81446cb3733a620983a/dotnet-runtime-3.0.0-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "d37dd8d3918d6463abdc7084fa51fe2b"
SRC_URI[sha256sum] = "dea07b9c3cb102c042f3c4b9a500347bdbf214f03e78dfe9738de974544fffa1"

