###################################################################################################
# Contains the URL and checksums to download version 5.0.4 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/5a496e41-23da-4aaa-94a7-baa9ab619fc6/0d000727345f3f71858ee79367f6ec23/dotnet-runtime-5.0.4-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "a593b895b70546161f15f6ba3218aac3"
SRC_URI[sha256sum] = "c4ff23491ed49030206b482b8cf229de0d6dc14c64957c8912328eab6c460f5e"
