###################################################################################################
# Contains the URL and checksums to download version 2.2.8 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/9f21e352-9d2c-4e3b-af45-915da89158db/0e8a7ea83cc08d4bcf417a927a36ed6f/dotnet-runtime-2.2.8-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "2a0e638edca3fac5313abd2508593cf6"
SRC_URI[sha256sum] = "ee45d30c533d7f4036b1ce8b024c5b1229ddb7186975b7bce01d3fc5a5498c6f"
