###################################################################################################
# Contains the URL and checksums to download version 5.0.0 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/66db1966-cbe4-4c6c-9e73-80305c555aba/faabab630f9f56e28e9dc30691bda72c/dotnet-runtime-5.0.4-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "C81623A015A45F54C48FE900CC7AF1C8"
SRC_URI[sha256sum] = "33D0918098B8261CB7C95604CC3DD05CC8EA1A79FBCF5630EBC9082ADFB2E880"
