###################################################################################################
# Contains the URL and checksums to download version 6.0.11 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/e208f394-bcb6-4ea9-8865-9fa2ed065d0a/5214d4e078744bbb3eea12c259b1d8cd/dotnet-runtime-6.0.11-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "bca34c0fb1d6433ce38f32c1145df327"
SRC_URI[sha256sum] = "60f2f5deacccde74069c48dfa0e6e0e82138c70b639a6aa7c77007bf4f109a17"
