###################################################################################################
# Contains the URL and checksums to download version 2.2.5 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/7aca89ca-5196-4b89-93bc-1ee1eeb251d7/ca4ff94c8692a6846a756fc07174974d/dotnet-runtime-2.2.5-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "7e5f167c28fbc748d6dda25518b27861"
SRC_URI[sha256sum] = "7b563a1a480feaad288b1ecf77c78f40537b5b688d8699a70272809e3a22ad9b"

