###################################################################################################
# Contains the URL and checksums to download version 7.0 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Sequent Logic 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/9ba81ab4-6e22-45bd-9c0b-c4ad46918e97/3b5a3d47243f3fb1bcc4ebbf1b08b08c/dotnet-runtime-7.0.0-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "3ef0439c33f431f3c7b13d09e5048415"
SRC_URI[sha256sum] = "700b5c03b9f46daf0c24a1652253860c63c2bbff2b6d3d3b7c674336a8eb4086"
