###################################################################################################
# Contains the URL and checksums to download version 5.0.0 of the ARM .Net Core runtime from
# Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/5fc4659b-86c2-4e8f-b409-853e6d8224a5/6de0fc8c6e26f308bf246aaa967c9fc1/dotnet-runtime-5.0.0-linux-arm.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "152c44f005e278761069263b97d0057b"
SRC_URI[sha256sum] = "884396d54545d2033c491fc4a63395e7c4b3122ccf3a06bdc1d92369ef2f97a6"
