###################################################################################################
# Contains the URL and checksums to download version 2.2.2 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/97b97652-4f74-4866-b708-2e9b41064459/7c722daf1a80a89aa8c3dec9103c24fc/dotnet-runtime-2.2.2-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "68fb4edc5e2eee02a5bfc896298f32b1"
SRC_URI[sha256sum] = "c9e132e78c5abc2470523228d9cbd48d63599831ff737e739e0ccbeceb5b0513"

