###################################################################################################
# Contains the URL and checksums to download version 3.0.0 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/89ac182b-199f-4b66-abf8-b0494407d890/c4dfc2ce4df1f7dad8d695c92562ab79/dotnet-runtime-3.0.0-preview5-27626-15-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "3480eac39ef75ab93653a22bf68d16da"
SRC_URI[sha256sum] = "98fdb84d695376eb0ea925174620ac995c98eed444d625875add6e59267e04e4"

