###################################################################################################
# Contains the URL and checksums to download version 2.1.3 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2018
###################################################################################################
SRC_URI = "https://download.microsoft.com/download/6/E/B/6EBD972D-2E2F-41EB-9668-F73F5FDDC09C/dotnet-runtime-2.1.3-linux-x64.tar.gz"

SRC_URI[md5sum] = "3a03eb0175a09c78d13d655582d2d325"
SRC_URI[sha256sum] = "dd5d52fdc439fce37b2cc706ecdaf8900c36870654bbce4ae693a66279821b2e"

