###################################################################################################
# Contains the URL and checksums to download version 5.0.14 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2022
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/c7e0c48d-e0ce-4ef9-b30b-41a66a078b0a/26cba85b178af0458f09830a93ab956b/dotnet-runtime-5.0.14-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "6e596fd7f754d2c2dc50b3db532d14cd"
SRC_URI[sha256sum] = "4e8b468612c6903167c729f32f41d2b0e703fec767e165ed9d5038da6e92d579"
