###################################################################################################
# Contains the URL and checksums to download version 2.2.5 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/21968111-f65e-48c7-9c35-8b40de4af06c/66b7a2c7b92b54bd3311f4509cc9b9ed/dotnet-runtime-2.2.5-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "e27dff144c6c19fe05961315d1e621de"
SRC_URI[sha256sum] = "a49ebecf9b1a4cadd47e4db65ae63425b94be75628314107def3abf52d5d0221"

