###################################################################################################
# Contains the URL and checksums to download version 2.2.7 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/9f21e352-9d2c-4e3b-af45-915da89158db/0e8a7ea83cc08d4bcf417a927a36ed6f/dotnet-runtime-2.2.7-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "9769909cb289369d7dc87b23385d967d"
SRC_URI[sha256sum] = "8d63e8d1bd3c811a6c11d41f3b8bdcdf69f8af40e5baafd505dd4c34da8cec87"

