###################################################################################################
# Contains the URL and checksums to download version 2.2.8 of the x86 64-bit .Net Core runtime
# from Microsoft.
# Copyright Matthijs de Ridder 2019
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/3fbca771-e7d3-45bf-8e77-cfc1c5c41810/e118d44f5a6df21714abd8316e2e042b/dotnet-runtime-2.2.8-linux-x64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "2a0e638edca3fac5313abd2508593cf6"
SRC_URI[sha256sum] = "ee45d30c533d7f4036b1ce8b024c5b1229ddb7186975b7bce01d3fc5a5498c6f"
