###################################################################################################
# Contains the URL and checksums to download version 3.1.1 of the ARM 64-bit .Net Core runtime
# from Microsoft.
# Copyright Richard Dunkley 2020
###################################################################################################
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/f6ca8333-82a2-4380-9d47-e152f47e85b8/1e3f6e0149761e884f63b14fa9d921f3/dotnet-runtime-3.1.9-linux-arm64.tar.gz;subdir=dotnet-${PV}"

SRC_URI[md5sum] = "4dd660ad8318a9cf0c92c3d4d6439e94"
SRC_URI[sha256sum] = "77536075b393cc02e1c1446fe560bff3b55f5e80b3d6dc4a3cc70b2231af5811"

